name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # ---------------------------
      # 1. Checkout Code
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------------
      # 2. Setup Python (for dependencies)
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ---------------------------
      # 3. Install dependencies (for building staticfiles)
      # ---------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---------------------------
      # 4. Build Docker Image
      # ---------------------------
      - name: Build Docker image
        run: |
          echo "Building Docker Image..."
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest .

      # ---------------------------
      # 5. Login to Docker Hub
      # ---------------------------
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # ---------------------------
      # 6. Push Image to Docker Hub
      # ---------------------------
      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest

      # ---------------------------
      # 7. Deploy to EC2
      # ---------------------------
      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/AWS_Ticket_System
            echo "Pulling latest docker image..."
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/django-app:latest
            docker compose up -d --build
            docker system prune -f
